name: Build and Deploy to Cloud Run
# いつワークフローを実行するかの設定
on:
  push:
    # masterブランチにプッシュされたタイミング
    branches: [ master ]
# 環境変数
env:
  SERVICE_NAME: my-cloudrun-app
  REGION: asia-northeast1
# 実行する作業の定義
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # コードを取得するステップ
    - name: Checkout code
      uses: actions/checkout@v3
    # Googleの認証をするステップ
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    # Google Cloud SDKによるコマンドを利用できるようにする
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    # Dockerイメージをビルドしてアップロード
    - name: Build and Push Container
      run: |-
        gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    # Cloud Runにデプロイ
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated
