# ワークフローの名前
name: Build and Deploy to Cloud Run

# 実行トリガ設定
on:
  push:
    # masterブランチにプッシュされたときだけ実行
    branches: [ master ]

# 環境変数の設定（全ステップから参照可能）
env:
  SERVICE_NAME: my-cloudrun-app  # Cloud Runのサービス名
  REGION: asia-northeast1        # デプロイするリージョン

# 実行する作業（ジョブ）の定義
jobs:
  # ジョブ名
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # ステップ1: GitHubからコードを取得
    - name: Checkout code
      uses: actions/checkout@v3  # v3は最新の安定バージョン
    
    # ステップ2: GCPの認証を行う
    - name: Google Auth
      id: auth  # このステップのID（他のステップから参照可能）
      uses: google-github-actions/auth@v1  # v1は最新の安定バージョン
      with:
        # GitHub Secretsから認証情報を取得
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    # ステップ3: Google Cloud SDKをセットアップ
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1  # v1は最新の安定バージョン
    
    # ステップ4: ローカルでDockerコンテナをビルドしてGCRにプッシュ
    - name: Build Container using local Docker
      run: |
        # Dockerfileからイメージをビルド
        docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest .
        # GCRへの認証を設定
        gcloud auth configure-docker
        # ビルドしたイメージをGCRにプッシュ
        docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
    
    # ステップ5: Cloud Runにデプロイ
    - name: Deploy to Cloud Run
      run: |
        # Cloud Runサービスをデプロイ
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated  # 認証なしでアクセス可能に設定
