name: Build and Deploy to Cloud Run
on:
  push:
    branches: [ master ]
env:
  SERVICE_NAME: my-cloudrun-app
  REGION: asia-northeast1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}  # シークレットから取得

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Debug Authentication
      run: |
        echo "Current project: $(gcloud config get-value project)"
        echo "Current account: $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"

    - name: Deploy to Cloud Run
      run: |
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --project ${{ secrets.PROJECT_ID }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated
